/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PrimeAvatar: typeof import('primevue/avatar')['default']
    PrimeButton: typeof import('primevue/button')['default']
    PrimeCheckbox: typeof import('primevue/checkbox')['default']
    PrimeDrawer: typeof import('primevue/drawer')['default']
    PrimeFieldset: typeof import('primevue/fieldset')['default']
    PrimeFloatLabel: typeof import('primevue/floatlabel')['default']
    PrimeIconField: typeof import('primevue/iconfield')['default']
    PrimeInputIcon: typeof import('primevue/inputicon')['default']
    PrimeInputText: typeof import('primevue/inputtext')['default']
    PrimeMenu: typeof import('primevue/menu')['default']
    PrimePanelMenu: typeof import('primevue/panelmenu')['default']
    PrimeTab: typeof import('primevue/tab')['default']
    PrimeTabList: typeof import('primevue/tablist')['default']
    PrimeTabPanel: typeof import('primevue/tabpanel')['default']
    PrimeTabPanels: typeof import('primevue/tabpanels')['default']
    PrimeTabs: typeof import('primevue/tabs')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    Ripple: typeof import('primevue/ripple')['default']
  }
}
